### ISSUE TITLE
Support alerts for API Gateway metrics

### ISSUE THREAD

**Issue by chrisandrews7** [ACloudGuru/serverless-plugin-aws-alerts#104]
Would be great to be able to add alarms to functions that have [http events](https://serverless.com/framework/docs/providers/aws/events/apigateway#simple-http-endpoint) for things like high 4xx, 5xx, latency etc.

**Comment by martrik** [comment]
Actually, the plugin nearly supports them. You would be able to configure them like this:
```yaml
 - name: function5XX
        description: '5XX response codes'
        namespace: 'AWS/ApiGateway'
        metric: 5XXError
        dimensions:
          - Name: ApiName
            Value: apiv1
          - Name: Resource
            Value: /api/{param}/hello
          - Name: Method
            Value: POST
          - Name: Stage
            Value: prod
        threshold: 5
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
```

However, the plugin adds an extra dimension by [default](https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/master/src/naming.js#L27) (`functionName`) to every alarm, which shouldn't be passed for API Gateway.

Therefore, a single modification to the plugin so that `functionName` can be removed would allow API Gateway metrics.
