### ISSUE TITLE
Cannot update existing alarms with new default function invocations values

### ISSUE THREAD

**Issue by disrael** [ACloudGuru/serverless-plugin-aws-alerts#118]
# This is a Bug Report
## Description
```
custom:
  alerts:
    topics:
      alarm:
        topic: uclusion-summaries-${opt:stage, self:provider.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: support@uclusion.com
    definitions:
      functionInvocations:
        evaluationPeriods: 60
        datapointsToAlarm: 10
    alarms:
      - functionErrors
      - functionThrottles
```
Alarms were created fine initially but later added the functionInvocations section and that had no effect
For bug reports:
* What went wrong?
Update of the alarms with the new defaults did not happen.
* What did you expect should have happened?
That the alarms would have the new defaults for evaluationPeriods and datapointsToAlarm
* What was the config you used?
See above.
* What stacktrace or error message from your provider did you see?
None

* Similar or dependent issues:
Didn't see any
