### ISSUE TITLE
How add a metrics of Metric Log Filters into dashboard?

### ISSUE THREAD

**Issue by coolboy0961** [ACloudGuru/serverless-plugin-aws-alerts#138]
Is there anyway to add a metrics of Metric Log Filters into dashboard?
I created a customized metrics like flowing, but in dashboard I only can find Errors,Throttles,Invocations and Duration.

```
custom:
  alerts:
    definitions:
      functionThrottles:
        treatMissingData: notBreaching
      functionErrors:
        treatMissingData: notBreaching
      functionInvocations:
        treatMissingData: notBreaching
      functionDuration:
        threshold: 5000
        treatMissingData: notBreaching

      applicationErrors:
        metric: ApplicationErrors
        threshold: 0
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanThreshold
        treatMissingData: notBreaching
        pattern: "ERROR"

    alarms:
      - applicationErrors
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration
```
