### ISSUE TITLE
[Question] Alarm for 4XXError in AWS API Gateway

### ISSUE THREAD

**Issue by pradeeptk304** [ACloudGuru/serverless-plugin-aws-alerts#146]
This is a Question/Bug report

I am trying to create an alarm to monitor 4XX errors from AWS API Gateway. I used the following block

```
provider:
  name: aws
  apiGateway:
    metrics: true

custom:
  alerts:
    nameTemplate: $[functionName]-$[metricName]-alarm
    prefixTemplate: $[stackName]
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts
        notifications:
          - protocol: email
            endpoint: some@email.com
    definitions:
      apiErrors:
        namespace: 'AWS/ApiGateway'
        metric: '4XXError'
        period: 60
        type: 'static'
        threshold: 1
        statistic: 'Sum'
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: 'GreaterThanOrEqualToThreshold'
    alarms:
      - apiErrors
```

I see the alarm is created but it stays under "Insufficient data" state. Email subscription was confirmed. I made sure API Gateway request failed with 401 but never got the email.

If possible, could you please provide an example?
