### ISSUE TITLE
SNS Topic Ref to AWS Clouformation

### ISSUE THREAD

**Issue by jbrads11** [ACloudGuru/serverless-plugin-aws-alerts#154]
We are trying to Ref to CloudFormation topic and we are getting TypeError: topic.indexOf is not a function.

Our code looks like this:

```
Set SNS Topics
topics:
  alarm:
    topic:
      Ref: AlarmTopic
resources:
  Resources:
    AlarmTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ${self:service}-${opt:stage}-alerts-alarm
        TopicName: ${self:service}-${opt:stage}-alerts-alarm
        KmsMasterKeyId: tester/key
        Subscription:
          - Endpoint: test23@gmail.com
            Protocol: EMAIL
```
