### ISSUE TITLE
FeatureRequest: allow enabled: false for custom alarms

### ISSUE THREAD

**Issue by nicodh** [ACloudGuru/serverless-plugin-aws-alerts#165]
According to the documentation it is possible to disable a default alarm on function level.
That would be useful fur self defined alarms also. 

```yaml

alerts:
   definitions:  
      customAlarm:
        ...
      alarms:
         - customAlarm

functions:
   handlerSpecial:
      alarms:
         - customAlarm:
              enabled: false
```
This is not possible right now with 1.7.1
