### ISSUE TITLE
Serverless reports configuration errors for 'alarms' property during validation

### ISSUE THREAD

**Issue by MattFisher** [ACloudGuru/serverless-plugin-aws-alerts#167]
# This is a Bug Report

## Description
When running `sls deploy` with a configuration that includes an `alarms` property on a function, the [service configuration validation](https://www.serverless.com/framework/docs/configuration-validation/) process throws a Configuration error saying the property is unrecognised.

This error doesn't seem to affect functionality - the specified alarms work when deployed.

It does prevent use of the stricter `configValidationMode: error`, because deployments are aborted when errors are raised in that setup.

I don't have experience writing serverless plugins, but there is [documentation for extending the validation schema](https://www.serverless.com/framework/docs/providers/aws/guide/plugins#extending-validation-schema) and it looks like the specific api is [defineFunctionProperties](https://www.serverless.com/framework/docs/providers/aws/guide/plugins#definefunctionproperties-helper). 

For bug reports:
* What went wrong?
A Configuration error is thrown.
* What did you expect should have happened?
No errors should occur.
* What was the config you used?
Relevant snippet:
```yaml
plugins:
  - serverless-plugin-aws-alerts

# ...

custom:
  alerts:
    topics:
      critical:
        alarm:
          topic:
            criticalalertsnstopic
      nonCritical:
        alarm:
          topic:
            notificationsnstopic
    definitions:
      criticalFunctionErrors:
        namespace: 'AWS/Lambda'
        metric: Errors
        threshold: 20
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        alarmActions:
          - critical
      functionErrors:
        alarmActions:
          - nonCritical
      functionThrottles:
        alarmActions:
          - nonCritical
    alarms:
      - functionErrors
      - functionThrottles
      - 
# ...

  myFunction:
    name: my_function
    handler: handlers.handle_my_function
    alarms:
      - criticalFunctionErrors
# ...
```

* What stacktrace or error message from your provider did you see?
```
  Serverless Error ---------------------------------------
 
  Configuration error: 
       at 'functions.myFunction': unrecognized property 'alarms'
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com
 
  Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              12.14.1
     Framework Version:         2.28.7 (local)
     Plugin Version:            4.4.3
     SDK Version:               2.3.2
     Components Version:        3.7.2
```
