### ISSUE TITLE
Ability to specify a topic name on a definition.

### ISSUE THREAD

**Issue by DavidAmesPup** [ACloudGuru/serverless-plugin-aws-alerts#18]
We have a scenario where we want all "normal" alerts to go to 1 email inbox and then when things go really wrong, we want an alert to a different email address (using an email -> sms gateway).

Example of what I am thinking:

custom:
notifications:
- protocol: email
endpoint: xxxx@yyyyy.slack.com
codeRedNotifications:
- protocol: email
endpoint: 11223344556677@messagenet.com

topics:
  alarm:
    topic: ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm
    notifications: ${self:custom.notifications}
  codeRed:
    topic: ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm-code-red
    notifications: ${self:custom.codeRedNotifications}

  function:
    namespace: 'AWS/Lambda'
    metric: Errors
    threshold: 1
    statistic: Sum
    period: 300
    evaluationPeriods: 1
    comparisonOperator: GreaterThanOrEqualToThreshold

  functionCodeRed:
    namespace: 'AWS/Lambda'
    metric: Errors
    threshold: 5
    statistic: Sum
    period: 300
    evaluationPeriods: 1
    comparisonOperator: GreaterThanOrEqualToThreshold
    topic: codeRed

**Comment by johncmckim** [comment]
Hey @DavidAmesPup thanks for adding this issue. I like the idea of being able to escalate an issue but I'm not sure how this will actually work.

CloudWatch alarms have three states `OK`, `Alarm` and `InsufficientData`. This is why there are only three topics.

If we were to allow people to add arbitrary topics I'm not sure how we would trigger each alarm.

Perhaps we can allow people to configure custom topics on an alarm definition as below. What do you think of this?

```yaml
# These become defaults
topics:
  ok: ${self:service}-${opt:stage}-alerts-ok
  alarm: ${self:service}-${opt:stage}-alerts-alarm
  insufficientData: ${self:service}-${opt:stage}-alerts-insufficientData
definitions:  # these defaults are merged with your definitions
  functionErrors:
    period: 300 # override period
  functionCodeRed:
    namespace: 'AWS/Lambda'
    metric: errors
    threshold: 5
    statistic: Sum
    period: 300
    evaluationPeriods: 1
    comparisonOperator: GreaterThanThreshold
    topics: # Able to override topics on the definition
      ok:
         topic: ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm-code-red
         notifications: ${self:custom.codeRedNotifications}
      alarm:
        topic: ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm-code-red
        notifications: ${self:custom.codeRedNotifications}
      insufficientData:  ${self:service}-${opt:stage, self:provider.stage}-alerts-alarm-code-red
    
```
