### ISSUE TITLE
externalStack not working properly

### ISSUE THREAD

**Issue by jmelendez-cbs** [ACloudGuru/serverless-plugin-aws-alerts#185]
# This is a Bug Report

## Description

When using the externalStack property I am getting the following messages from serverless:

```
Serverless: Removing external alert stack ee-override-nba-dev-alerts (no resources configured)...
Serverless: External alert stack ee-override-nba-dev-alerts removed successfully.
Serverless: Removing old service artifacts from S3...
```
My serverless yaml looked like this:

```
plugins:
  - serverless-plugin-aws-alerts

custom:
  alerts:
    dashboards: true
    externalStack: true
```
Has anyone else seen/solved this issue?
