### ISSUE TITLE
Alert topics not resolved from parameter store

### ISSUE THREAD

**Issue by sopeters** [ACloudGuru/serverless-plugin-aws-alerts#208]
I'm having trouble to lookup the topics from parameter-store which seemed to have worked in a previous version.
The actual Alarms are created but the Actions are missing.

```
service: test
variablesResolutionMode: 20210326
frameworkVersion: '2'

custom:
  alerts:
    topics:
      ok: ${ssm:/default/SNSNotificationListARN}
    alarms:
      - functionErrors

plugins:
  - serverless-plugin-aws-alerts
```

* ***Serverless Framework Version***: 2.68.0
* ***serverless-plugin-aws-alerts***: 1.7.4
