### ISSUE TITLE
Add support for step functions alarms

### ISSUE THREAD

**Issue by bhedia** [ACloudGuru/serverless-plugin-aws-alerts#214]
# This is a Feature Proposal

## Serverless supports deploying AWS Step Functions, but this plugin does not seem to support adding CW alarms for Step Functions. When I try to use it, here's what I get:

```yaml
custom:
  regionAlias: ${opt:regionAlias, 'uw1'}
  alerts:
    topics:
      alarm:
        topic: arn:aws:sns:#{AWS::Region}:#{AWS::AccountId}:alarm-topic-${self:provider.stage}
    definitions:
      executionsTimedOut:
        namespace: 'AWS/States'
        metric: ExecutionsTimedOut
        threshold: 1
        statistic: Sum
        period: 3600
        evaluationPeriods: 1
        datapointsToAlarm: 1
        comparisonOperator: GreaterThanOrEqualToThreshold
        treatMissingData: missing
    alarms:
      - executionsTimedOut

stepFunctions:
  stateMachines:
    helloWorld:
      alarms:
        - executionsTimedOut
      definition:
        StartAt: SayHelloWorld
        States:
          SayHelloWorld:
            Type: Pass
            End: true
``` 

`State machine [helloWorld] is malformed. Please check the README for more info. ValidationError: child "alarms" fails because ["alarms" must be an object]`
