### ISSUE TITLE
Add support for external created API Gateway

### ISSUE THREAD

**Issue by lucasvieirasilva** [ACloudGuru/serverless-plugin-aws-alerts#215]
# This is a Feature Proposal

## Description

Currently, this plugin uses the stage and service name to build the API gateway name.

Code reference: https://github.com/ACloudGuru/serverless-plugin-aws-alerts/blob/master/src/dashboards/widgets/api-gw/requests/numbers.js#L2

But will be nice to support API gateway created externally.

In the alarms configuration section the `apiName` could be an optional property, like this:

```yaml
custom:
  alerts:
    dashboards: true
    dashboardConfig: 
      apiName: 'my-custom-api-gateway-name'
```
