### ISSUE TITLE
send email to multiple developers on getting an alarm

### ISSUE THREAD

**Issue by suku-h** [ACloudGuru/serverless-plugin-aws-alerts#23]
The following code doesn't work 
`  notifications:
    - protocol: email
      endpoint:
        - sukumar.honkote@sv.com
        - mehul@sv.com`

Endpoint takes only string and not a list. How can I send alarm to both of them?

**Comment by johncmckim** [comment]
Hi @suku-h you should be able to acheive that like so

```yaml
notifications:
    - protocol: email
      endpoint: sukumar.honkote@sv.com
    - protocol: email
      endpoint: mehul@sv.com
```
