### ISSUE TITLE
Dashboards doesn't work with a custom lambda names

### ISSUE THREAD

**Issue by NevRA** [ACloudGuru/serverless-plugin-aws-alerts#233]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? No data in the dashboard. Looks like all widgets were created with the wrong function names.
Example (my yml template):
```
Func:
  ...
  name: my-func
```

In the widget details, I see Func (FunctionName) but should be my-func. So I think this is a reason why there is no data in the dashboard, because no such functions. If I create dashboard widget manually with a correct func name everything works correctly
* What did you expect should have happened? Name should be correct and data from functions should be available 
* What was the config you used?
```
  alerts:
    dashboards: true
    topics:
      alarm:
        topic: 
          Ref: AlarmsTopic
    alarms:
      - functionErrors
      - functionThrottles
```
* What stacktrace or error message from your provider did you see? - 

Similar or dependent issues:

## Additional Data

* ***Serverless Framework Version***: 3.17.0
* ***Stack Trace***: - 
* ***Provider Error messages***: No errors
