### ISSUE TITLE
Error: this.providerNaming.getLogGroupName is not a function

### ISSUE THREAD

**Issue by flpStrri** [ACloudGuru/serverless-plugin-aws-alerts#24]
I'm getting a `this.providerNaming.getLogGroupName is not a function` on deployment. There is something wrong with my setup?

```yml
service: gdw-pump-webhook

provider:
  name: aws
  runtime: python2.7
  memorySize: 128
  timeout: 10
  region: ${env:AWS_DEFAULT_REGION}
  deploymentBucket: com.zx-ventures.${env:AWS_DEFAULT_REGION}.serverless.deploys
  iamRoleStatements:
    - Effect: Allow
      Action:
        - kinesis:GetRecords
        - kinesis:GetShardIterator
        - kinesis:PutRecord
        - kinesis:PutRecords
        - kinesis:DescribeStream
        - kinesis:ListStreams
        - firehose:DeleteDeliveryStream
        - firehose:PutRecord
        - firehose:PutRecordBatch
        - firehose:UpdateDestination
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
      Resource: '*'
  stackPolicy:
    - Effect: Allow
      Principal: "*"
      Action: "Update:*"
      Resource: "*"
    - Effect: Deny
      Principal: "*"
      Action:
        - Update:Replace
        - Update:Delete
      Condition:
        StringEquals:
          ResourceType:
            - AWS::S3::Bucket

package:
  exclude:
    - tmp/**
    - .git/**
    - .env/**
    - tests/**
    - .cache/**
    - README.md
    - requirements.txt
    - .coveragerc
    - .gitignore
    - .travis.yml
    - htmlcov/**
    - coverage.xml
    - .coverage

custom:
  alerts:
    topics:
      ok: ${self:service}-${opt:stage}-alerts-ok
      alarm: ${self:service}-${opt:stage}-alerts-alarm
      insufficientData: ${self:service}-${opt:stage}-alerts-insufficientData
    function:
      - functionInvocations
      - functionDuration
      - name: functionExceptions
        metric: Exceptions
        threshold: 1
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: \"[ERROR]\"

plugins:
  - serverless-plugin-aws-alerts

functions:
  OrderLinePump:
    handler: lib.machinery.pump
    environment:
      REGION_NAME: ${env:AWS_DEFAULT_REGION}
      STREAM_NAME: ${self:resources.Resources.OrderLineInputStream.Properties.Name}
    events:
      - http:
          path: notification
          method: post
          private: true
          cors: true

  OrderLineValidatedPipe:
    handler: lib.machinery.lake_pipe
    environment:
      REGION_NAME: ${env:AWS_DEFAULT_REGION}
      STREAM_NAME: ${self:resources.Resources.OrderLineFirehoseDeliveryStream.Properties.DeliveryStreamName}
    events:
      - stream:
          arn: arn:aws:kinesis:${env:AWS_DEFAULT_REGION}:${env:AWS_ACCOUNT_ID}:stream/${self:resources.Resources.OrderLineInputStream.Properties.Name}
          batchSize: 5
          startingPosition: LATEST
          enabled: true
...
```
