### ISSUE TITLE
Add support for CloudFormation property ExtendedStatistic

### ISSUE THREAD

**Issue by nikgraf** [ACloudGuru/serverless-plugin-aws-alerts#33]
# This is a Feature Proposal

## Description

CloudFormation now supports `ExtendedStatistic`. Would be great to have it in here http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cw-alarm.html#cfn-cloudwatch-alarms-extendedstatistic

**Comment by johncmckim** [comment]
@nikgraf I've been thinking about how this should be implemented. Ideally I think the difference between `Statistic` and `ExtendedStatistic` should be transparent to the user.

It would be great if we could let people create alarms like below. This would use `ExtendedStatistc` behind the scenes.

We could also add some validation to the statistic to throw an error prior to deployments.

```yml
customAlarm:
        description: 'My custom alarm'
        namespace: 'AWS/Lambda'
        metric: duration
        threshold: 200
        statistic: p50
        period: 300
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
```
