### ISSUE TITLE
Unresolved resource dependencies [AwsAlertsAlarm] in the Resources block of the template

### ISSUE THREAD

**Issue by jaekunchoi** [ACloudGuru/serverless-plugin-aws-alerts#44]
I'm getting   The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [AwsAlertsAlarm] in the Resources block of the template

I've got all the config as per the guide but it doesn't seem to create any sns topic resource?

Below is my config. I had a look at S3 Cloudformation template but I couldn't see any resource of AwsAlertsAlarm which is the reason why this is failing
```

service: testing-backend

provider:
  name: aws
  region: us-east-1
  runtime: nodejs6.10

plugins:
  - serverless-aws-alias
  - serverless-plugin-aws-alerts

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: testing@gmail.com
    definitions:
      geneticErrors:
        metric: GenericErrors
        threshold: 0
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        treatMissingData: notBreaching
        pattern: 'Error'
    alarms:
      - functionErrors
      - functionThrottles
      - geneticErrors

functions:
  test:
    handler: lambda.next
```
