### ISSUE TITLE
Custom metric with alarm

### ISSUE THREAD

**Issue by RastoStric** [ACloudGuru/serverless-plugin-aws-alerts#45]
I am trying to use the plugin to create a custom metric and an alarm based on that metric. Deploy goes with no error but none of those gets created. `sls deploy --verbose` does not produce anything related to it.
This is my `serverless.yml`
```
...
plugins:
  - serverless-plugin-aws-alerts

custom:
  alerts:
    function:
      - name: Error500Alarm
        metric: Error500
        threshold: 0
        statistic: Minimum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'METRIC Error500'

functions:
  products:
    handler: functions/product/product_lambda.router
    vpc: ${file(../params.yml):${self:custom.stage}.VPC}
    alarms:
      - Error500Alarm
    events:
...
```

I have probably misunderstood your description and must be doing something wrong, but googling nor reading issues here did not help.

* ***Serverless Framework Version***: 1.8.0

Thank you

**Comment by WirthAware** [comment]
@RastoStric from your posted sys config it looks like you forgot to determine the stage to deploy alarms to 

```yaml
custom:
  alerts:
    stages: # Optionally - select which stages to deploy alarms to
      - producton
      - staging
... # rest of your config here
```

Alarms only deployed to the configured `stages`

**Comment by RastoStric** [comment]
@WirthAware  Thank you for your reply, meanwhile I got it working like this:
```
...
custom:
  alerts:
    definitions:
      Error500:
        description: 'Error500'
        metric: Error500
        threshold: 0
        statistic: Average
        period: 300
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: 'METRIC Error500'
    topics:
      alarm:
        topic: ${self:service}-${self:custom.stage}-alerts-alarm
        notifications:
          - protocol: email
            endpoint: ...
          - protocol: email
            endpoint: ...

functions:
  products:
    handler: functions/product/product_lambda.router
    alarms:
      - Error500
...
```
