### ISSUE TITLE
How to redeploy/Update Alarm

### ISSUE THREAD

**Issue by jseiser** [ACloudGuru/serverless-plugin-aws-alerts#50]
I installed the plugin, added some of your defaults to me serverless.yml file, deployed and everything went fine.  I pull in my SNS topics from a SSM Parameter store and realized I must have left a space at the end of the paramter.  So the alarms deployed, but the SNS topic was invalid.  I updated the parameter store, redeployed the entire service and the SNS topic was still referencing the invalid topic in the alarm.

Is there a way to re-deploy the cloudwatch alarms without having to remove and re-deploy the service?

```
environment:
    commonSNS: ${ssm:commonSNS}

custom:
  enabled:
    dev: false
    prod: true
  
  alerts:
    stages:
      - dev

    dashboards: true

    topics:
      alarm: ${ssm:jiraSNS}
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

plugins:
  - serverless-plugin-aws-alerts
```

Thats the relevant portion of my serverless file.  The ${ssm:jiraSNS} parameter was the one that must have had a space at the end of the string, which I removed and was hoping would get picked up when I deployed the service again.
