### ISSUE TITLE
Metric Filter configuration producing unexpected results

### ISSUE THREAD

**Issue by JBartlett86** [ACloudGuru/serverless-plugin-aws-alerts#53]
# This is a Bug Report

## Description

I am trying to configure a metric filter alarm with a given filter pattern for the function under my service, 

```
custom:
  alerts:
    topics:
      alarm: 
        topic: arn:aws:sns:eu-west-1:704255512929:CloudWatch-ErrorLogs
    function:
      - name: AnAlarm
        metric: AnError
        treatMissingData: notBreaching
        threshold: 0
        statistic: Sum
        period: 60
        evaluationPeriods: 1
        comparisonOperator: GreaterThanThreshold
        pattern: '[ERROR]'
```
I was expecting this to create a single metric filter (ERROR) linked a single alarm that is then linked to an SNS Topic (CloudWatch-ErrorLogs), however what is actually happening is 2 metric filters are being created, one with a suffix **ALERT** and another with a suffix **OK**.
Both of these are then linked to the same metric and the same alert.

I'm not entirely sure how it's ended up creating the OK metric filter but I definitely do not want it.
Any help would be greatly appreciated?

## Additional Data

* ***Serverless Framework Version: 1.26.0***:
