### ISSUE TITLE
Alert Emails Duplicated in CloudWatch Alarms

### ISSUE THREAD

**Issue by ctg3** [ACloudGuru/serverless-plugin-aws-alerts#74]
# This is a Bug Report

## Description

For bug reports:
* What went wrong? 

Email address is listed multiple times within the actions of the alarm in CloudWatch (i.e "Send message to topic "service-stage-alerts-alarm" (email@company.com)" is listed 2+ times for "ALARM", "OK", and "INSUFFICENT DATA")

This seems to occur when the alarms are removed and then re-added or the service is removed and then re-deployed.

When I go to the SNS topic, it only shows one email address subscribed.

* What did you expect should have happened? 

Email address should only appear once.

* What was the config you used?

```
custom:
  alerts:
    email: name@company.com
    topics:
      ok:
        topic: ${self:service}-${self:provider.stage}-alerts-ok
        notifications:
        - protocol: email
          endpoint: ${self:custom.alerts.email}
      alarm:
        topic: ${self:service}-${self:provider.stage}-alerts-alarm
        notifications:
        - protocol: email
          endpoint: ${self:custom.alerts.email}
      insufficientData:
        topic: ${self:service}-${self:provider.stage}-alerts-insufficientData
        notifications:
        - protocol: email
          endpoint: ${self:custom.alerts.email}
```

* What stacktrace or error message from your provider did you see?

None

## Additional Data

* ***Serverless Framework Version***: 1.32.0
* ***Stack Trace***: None
* ***Provider Error messages***: None
