### ISSUE TITLE
Support import of CloudFormation exported SNS topics for AlarmActions

### ISSUE THREAD

**Issue by richardcornelissen** [ACloudGuru/serverless-plugin-aws-alerts#76]
# This is a Feature Proposal

## Description

For feature proposals:
* What is the use case that should be solved. The more detail you describe this in the easier it is to understand for us.

Aside from using arn's, add support to import CloudFormation exports as alarm actions for easy reference.

* If there is additional config how would it look

```
custom:
  alerts:
    topics:
      alarm:
        topic:
          Fn::ImportValue: ServiceMonitoring:monitoring-${opt:stage, 'dev'}
```

Similar or dependent issues:
* #14 includes arn support

## Additional Data

* ***Serverless Framework Version***: 1.32.0
* ***Stack Trace***: N/A
* ***Provider Error messages***: N/A
